
# appengine-deployment/app.yaml
runtime: python39
service: default

# Environment variables
env_variables:
  FLASK_ENV: production
  APP_TITLE: "Hello World - Azure AD Protected"

# Scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Health check configuration
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301