name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/245066890273/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@nonprod1-svc-gu0t.iam.gserviceaccount.com"
          
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: nonprod1-svc-gu0t
          
      # Build and Push with Cloud Build (regional)
      - name: Build and Push Docker image with Cloud Build
        run: |
          gcloud builds submit \
            --tag "gcr.io/nonprod1-svc-gu0t/cloudrun-demo:latest" \
            --region=us-east1 \
            --project=nonprod1-svc-gu0t \
            .
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloudrun-demo \
            --image "gcr.io/nonprod1-svc-gu0t/cloudrun-demo:latest" \
            --region us-east1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --project=nonprod1-svc-gu0t
