name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # 👈 needed for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/1234567890/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "sa-deployer@nonprod1-svc-gu0t.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: my-service
          image: us-central1-docker.pkg.dev/nonprod1-svc-gu0t/cloudrun-repo/my-app:latest
          region: us-central1
