name: Deploy to Cloud Run

on:
  push:
    branches:
      - main   # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC
      contents: read    # To checkout code

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate with GCP using Workload Identity Federation (OIDC)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/245066890273/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-deployer@nonprod1-svc-gu0t.iam.gserviceaccount.com"

      # Setup gcloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      # Build Docker image and push to Artifact Registry (or GCR)
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag "gcr.io/nonprod1-svc-gu0t/cloudrun-demo:latest" .

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloudrun-demo \
            --image="gcr.io/nonprod1-svc-gu0t/cloudrun-demo:latest" \
            --region=us-east1 \
            --platform=managed \
            --allow-unauthenticated
